# Install archlinux base image
FROM archlinux

# Set up conda environment variables
ENV \
    MINICONDA_SHA256=1ea2f885b4dbc3098662845560bc64271eb17085387a70c2ba3f29fff6f8d52f \
    CONDA_ROOT=/opt/conda \
    RESOURCES_PATH="/resources" \
    WORKSPACE_HOME="/workspace"


# Make folders
RUN \
    mkdir $WORKSPACE_HOME && chmod a+rwx $WORKSPACE_HOME


# Update base system then install python and wget
RUN \
    yes | pacman -Syu && \
    yes | pacman -S wget && \
    yes | pacman -S git
#    pacman -S base-devel --noconfirm


#    PATH "$CONDA_ROOT/bin:$PATH"
# Install miniconda https://docs.conda.io/en/latest/miniconda.html
# download the latest version
# check the sha256 checksum
# run miniconda installer specifying dir rather than user (root) folder
# add conda to path
# remove install file
RUN wget --no-verbose https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    echo "${MINICONDA_SHA256} /root/miniconda.sh" | sha256sum -c - && \
    /bin/bash ~/miniconda.sh -b -p $CONDA_ROOT && \
    export PATH=$CONDA_ROOT/bin:$PATH && \
    rm ~/miniconda.sh && \
    # Configure conda
    $CONDA_ROOT/bin/conda config --system --add channels conda-forge && \
    $CONDA_ROOT/bin/conda config --system --set auto_update_conda False && \
    $CONDA_ROOT/bin/conda config --system --set show_channel_urls True && \
    $CONDA_ROOT/bin/conda config --system --set channel_priority strict && \
    # Deactivate pip interoperability (currently default), otherwise conda tries to uninstall pip packages
    #    $CONDA_ROOT/bin/conda config --system --set pip_interop_enabled false && \
    # Update conda
    $CONDA_ROOT/bin/conda update -y -n base -c defaults conda && \
    $CONDA_ROOT/bin/conda update -y setuptools && \
    $CONDA_ROOT/bin/conda install -y conda-build && \
    # Update selected packages - install python 3.8.x
    #    $CONDA_ROOT/bin/conda install -y --update-all python=$PYTHON_VERSION && \
    # Link Conda
    ln -s $CONDA_ROOT/bin/python /usr/local/bin/python && \
    ln -s $CONDA_ROOT/bin/conda /usr/bin/conda && \
    # Update
    $CONDA_ROOT/bin/conda install -y pip && \
    $CONDA_ROOT/bin/pip install --upgrade pip && \
    chmod -R a+rwx /usr/local/bin/ && \
    # Cleanup - Remove all here since conda is not in path as of now
    # find /opt/conda/ -follow -type f -name '*.a' -delete && \
    # find /opt/conda/ -follow -type f -name '*.js.map' -delete && \
    $CONDA_ROOT/bin/conda clean -y --packages && \
    $CONDA_ROOT/bin/conda clean -y -a -f  && \
    $CONDA_ROOT/bin/conda build purge-all
    # Fix permissions
    #     fix-permissions.sh $CONDA_ROOT && \
    #     clean-layer.sh


# COPY resources/packages/visual-studio-code-bin-1.61.1-1-x86_64.pkg.tar.zst $RESOURCES_PATH/packages/visual-studio-deskop.pkg.tar.zst
# RUN yes | pacman -U $RESOURCES_PATH/packages/visual-studio-deskop.pkg.tar.zst


RUN useradd --no-create-home --shell=/bin/false build && usermod -L build
RUN echo "build ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER build
RUN git clone https://aur.archlinux.org/visual-studio-code-bin.git:$RESOURCES_PATH/packages/vs-code && cd $RESOURCES_PATH/packages/vs-code && makepkg -s
USER root
RUN pacman -U *.pkg.tar.zst